export const TOUR_STEPS = [
  {
    id: "dashboard",
    route: "/dashboard",
    target: "[data-tour=\"dashboard\"]",
    title: "Your command center",
    body: "The dashboard is your live trading HUD — portfolio value, AI signals, open positions, and performance at a glance.",
    placement: "bottom" as const,
  },
  {
    id: "bot-controls",
    route: "/dashboard",
    target: "[data-tour=\"bot-controls\"]",
    title: "Start the AI bot",
    body: "Tap Start Bot to run automatic market scans. Use Scan Now for a one-off scan without leaving the bot running.",
    placement: "bottom" as const,
  },
  {
    id: "signals",
    route: "/dashboard",
    target: "[data-tour=\"signals\"]",
    title: "AI signal feed",
    body: "When patterns exceed your confidence threshold, buy/sell signals appear here with strategy name and confidence score.",
    placement: "right" as const,
  },
  {
    id: "portfolio",
    route: "/dashboard",
    target: "[data-tour=\"portfolio\"]",
    title: "Portfolio tracking",
    body: "Track equity over 1D–1Y. Connect Alpaca to see your paper account balance, or use the built-in simulator.",
    placement: "left" as const,
  },
  {
    id: "watchlist-nav",
    route: "/dashboard",
    target: "[data-tour=\"nav-watchlist\"]",
    title: "Watchlist",
    body: "Next we will visit your watchlist — the symbols the bot scans for trade opportunities.",
    placement: "right" as const,
  },
  {
    id: "watchlist",
    route: "/watchlist",
    target: "[data-tour=\"watchlist-search\"]",
    title: "Build your watchlist",
    body: "Search stocks and crypto, then add symbols. The bot only scans tickers on your watchlist during market hours.",
    placement: "bottom" as const,
  },
  {
    id: "history-nav",
    route: "/watchlist",
    target: "[data-tour=\"nav-history\"]",
    title: "Trade history",
    body: "Every bot trade is logged — let us see where you review performance.",
    placement: "right" as const,
  },
  {
    id: "history",
    route: "/history",
    target: "[data-tour=\"trade-history\"]",
    title: "Review every trade",
    body: "Filter by open, win, or loss. Inspect entry/exit reasons, P&L, and close open positions at market.",
    placement: "bottom" as const,
  },
  {
    id: "settings-nav",
    route: "/history",
    target: "[data-tour=\"nav-settings\"]",
    title: "Settings & strategies",
    body: "Configure risk, timeframes, and which AI strategies run on your account.",
    placement: "right" as const,
  },
  {
    id: "strategies",
    route: "/settings",
    target: "[data-tour=\"strategies\"]",
    title: "Pick your strategies",
    body: "Enable stock and crypto strategies that match your style. Toggle experimental strategies for advanced patterns.",
    placement: "top" as const,
  },
  {
    id: "alpaca",
    route: "/settings",
    target: "[data-tour=\"alpaca-connect\"]",
    title: "Connect Alpaca anytime",
    body: "Paste your API keys here whenever you are ready. The step-by-step guide stays in this panel for reference.",
    placement: "top" as const,
  },
] as const;
